# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swamplr_jobs', '0006_auto_20170927_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='derivative_files',
            fields=[
                ('derive_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('source_file', models.CharField(max_length=255)),
                ('target_file', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='derivative_jobs',
            fields=[
                ('derive_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_dir', models.CharField(max_length=255)),
                ('replace_on_duplicate', models.CharField(max_length=1)),
                ('subset', models.IntegerField(default=0)),
                ('source_file_extension', models.CharField(max_length=10)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='derivative_results',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='job_derivatives',
            fields=[
                ('job_derive_id', models.AutoField(primary_key=True, serialize=False)),
                ('derive_type', models.CharField(max_length=32)),
                ('parameters', models.CharField(max_length=1024)),
                ('derive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_derivatives.derivative_jobs')),
            ],
        ),
        migrations.AddField(
            model_name='derivative_files',
            name='job_derive_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_derivatives.job_derivatives'),
        ),
        migrations.AddField(
            model_name='derivative_files',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_derivatives.derivative_results'),
        ),
        migrations.RunSQL("INSERT INTO swamplr_jobs_job_types (label, app_name) VALUES('derivatives', 'swamplr_derivatives') ON DUPLICATE KEY UPDATE label=label;"),
        migrations.RunSQL("INSERT INTO swamplr_derivatives_derivative_results (label) VALUES('Success'), ('Failure'), ('Skipped') ON DUPLICATE KEY UPDATE label=label;"),
    ]
