# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_datastreams',
            name='object_type',
            field=models.CharField(default='object', max_length=32),
            preserve_default=False,
        ),
    ]
