# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_ingest', '0002_job_datastreams_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_objects',
            name='datastream_id',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='swamplr_ingest.datastreams'),
            preserve_default=False,
        ),
    ]
