# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0006_auto_20170927_1709'),
        ('swamplr_ingest', '0003_job_objects_datastream_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='delete_jobs',
            fields=[
                ('delete_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.jobs')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_ingest.ingest_jobs')),
            ],
        ),
        migrations.CreateModel(
            name='delete_objects',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=64, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.jobs')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_ingest.object_results')),
            ],
        ),
        migrations.AddField(
            model_name='job_objects',
            name='new_object',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.RunSQL("INSERT INTO swamplr_jobs_job_types (label, app_name) VALUES('delete', 'swamplr_ingest') ON DUPLICATE KEY UPDATE label=label;"),
]
