# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0008_auto_20180221_1708'),
        ('swamplr_ingest', '0006_pathauto_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='pathauto_jobs',
            fields=[
                ('pathauto_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.jobs')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_ingest.ingest_jobs')),
            ],
        ),
    ]
