# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0008_auto_20180221_1708'),
        ('swamplr_ingest', '0007_pathauto_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='pathauto_objects',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=64, null=True)),
                ('generated', models.DateTimeField(null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.jobs')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_ingest.object_results')),
            ],
        ),
    ]
