# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 15:49
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0002_auto_20170906_1649'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO swamplr_jobs_job_types (label) VALUES('service') ON DUPLICATE KEY UPDATE label=label;"),
    ]

