# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_services', '0003_auto_20170913_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='frequency',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='last_started',
            field=models.DateTimeField(null=True),
        ),
    ]
