# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0004_job_types_app_name'),
        ('swamplr_services', '0004_auto_20170914_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_status',
            fields=[
                ('service_status_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swamplr_jobs.status')),
                ('status', models.CharField(max_length=32))]),
        migrations.RunSQL('INSERT INTO swamplr_services_service_status (service_status_id_id, status) SELECT status_id, status from swamplr_jobs_status;'),    
]
