# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_services', '0005_service_status'),
    ]

    operations = [
        migrations.RunSQL("UPDATE swamplr_jobs_job_types SET app_name='swamplr_services' WHERE label='services';"),
    ]
