# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_services', '0007_auto_20170915_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='auto_archive',
            field=models.BigIntegerField(null=True),
        ),
    ]
