# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_services', '0008_services_auto_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='archived',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
