# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_objects',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('obj_file', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='job_types',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('process_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('default', models.CharField(max_length=1)),
                ('failure', models.CharField(max_length=20)),
                ('running', models.CharField(max_length=1)),
                ('success', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.status'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.job_types'),
        ),
        migrations.AddField(
            model_name='job_objects',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.jobs'),
        ),
        migrations.AddField(
            model_name='job_messages',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.jobs'),
        ),
    ]
