# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_types',
            name='label',
            field=models.CharField(max_length=64, unique=True)),
    ]
