# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0002_auto_20170906_1649'),
    ]

    operations = [
        migrations.RunSQL("""INSERT INTO swamplr_jobs_status (status, `default`, failure, running, success) VALUES('Job Queued','y','','',''), ('Cancelled By User','','manual','',''), ('Failed due to timeout','','timeout','',''), ('Script error','','error','',''), ('Running','','','y',''), ('Success','','','','y');"""),
    ]
