# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0003_auto_20170912_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_types',
            name='app_name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
