# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0006_auto_20170927_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_types',
            name='app_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
