# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swamplr_jobs', '0006_auto_20170927_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='cache_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField(null=True)),
                ('last_run', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='namespace_cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=64)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='namespace_jobs',
            fields=[
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swamplr_jobs.jobs')),
                ('namespace', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='namespace_operations',
            fields=[
                ('operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='namespace_jobs',
            name='operation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_namespaces.namespace_operations'),
        ),
    ]
