# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_namespaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace_cache',
            name='namespace',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
