# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_namespaces', '0002_auto_20171130_1531'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO swamplr_jobs_job_types (label, app_name) VALUES('namespaces', 'swamplr_namespaces') ON DUPLICATE KEY UPDATE label=label;"),
        migrations.RunSQL("INSERT INTO swamplr_namespaces_namespace_operations (operation_name) VALUES('List'), ('Reindex'), ('Delete') ON DUPLICATE KEY UPDATE operation_name=operation_name;")
    ]
