# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_jobs', '0006_auto_20170927_1709'),
        ('swamplr_namespaces', '0003_auto_20171201_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='namespace_objects',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.DateTimeField()),
                ('pid', models.CharField(max_length=64, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_jobs.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='object_results',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='namespace_objects',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swamplr_namespaces.object_results'),
        ),
    ]
