# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swamplr_namespaces', '0004_auto_20171204_2205'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO swamplr_namespaces_object_results (label) VALUES('Success'), ('Failure'), ('Skipped') ON DUPLICATE KEY UPDATE label=label;")
    ]
